# Generated by Django 6.1 on 2026-08-17 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('district', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('area', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rooms', models.PositiveSmallIntegerField()),
                ('floor', models.PositiveSmallIntegerField()),
                ('year_built', models.PositiveSmallIntegerField()),
                ('market_type', models.CharField(choices=[('primary', 'Pierwotny'), ('secondary', 'Wtórny')], max_length=20)),
            ],
        ),
    ]
