# Generated by Django 6.1 on 2026-08-19 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='district',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='market_type',
            field=models.CharField(choices=[('primary', 'Pierwotny'), ('secondary', 'Wtórny'), ('unknown', 'Brak danych')], max_length=20),
        ),
        migrations.AlterField(
            model_name='apartment',
            name='year_built',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
