# Generated by Django 6.1 on 2026-08-19 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0002_alter_apartment_district_alter_apartment_market_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='source_id',
            field=models.CharField(blank=True, max_length=32, null=True, unique=True),
        ),
    ]
