# Generated by Django 6.1 on 2026-08-29 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0003_apartment_source_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='market_type',
            field=models.CharField(blank=True, choices=[('primary', 'Pierwotny'), ('secondary', 'Wtórny'), ('', 'Brak danych')], default='', max_length=20),
        ),
    ]
