# Generated by Django 6.1 on 2026-08-31 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0004_alter_apartment_market_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='floor_count',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
