# Generated by Django 6.1 on 2026-08-31 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0005_apartment_floor_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='has_balcony',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_elevator',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='has_parking',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
