# Generated by Django 6.1 on 2026-09-09 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0006_apartment_has_balcony_apartment_has_elevator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apartment',
            name='floor',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
