# Generated by Django 6.1 on 2026-09-09 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0007_alter_apartment_floor'),
    ]

    operations = [
        migrations.AddField(
            model_name='apartment',
            name='city_median_price_per_sqm',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price_difference_pct',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AddField(
            model_name='apartment',
            name='price_rating',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
