# Generated by Django 6.1 on 2026-09-16 08:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apartments', '0008_apartment_city_median_price_per_sqm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apartment',
            name='district',
        ),
    ]
